version: '3.8'
services:

  postgres:
    image: postgres:16
    container_name: sedreh-postgres1.2
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=postgres
    ports:
      - "5434:5432"  
    volumes:
      - postgres_data:/var/lib/postgresql/data


  redis:
    image: redis:alpine



  django:
    build: .
    container_name: sedreh_django_app
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DATABASE_URL=postgres://username:1234@postgres:5432/postgres
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    volumes:
      - .:/app



  celery:
    build: . 
    image: celery
    container_name: celery_sedreh
    command: celery --app sample_sedreh worker --concurrency=4
    environment:
      - DATABASE_URL=postgres://username:1234@db:5432/postgres
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - django
      - redis



volumes:
  postgres_data:
