# Generated by Django 4.2.16 on 2024-10-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpcode',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='otpcode',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
