# Generated by Django 4.2.16 on 2024-10-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_otpcode_is_active_otpcode_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpcode',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='otpcode',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
