# Generated by Django 4.2.16 on 2024-10-19 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otpcode',
            old_name='email',
            new_name='user',
        ),
    ]
