# Generated by Django 4.2.16 on 2024-10-19 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_email_otpcode_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
